{
 "title": "Welding Machine",
 "time": { "from": "now-1m", "to": "now" },
 "refresh": "1s",
 "panels": [
  {
   "title": "Angular Velocity and Forces",
   "type": "timeseries",
   "description": "Arrays Values of Angular Velocity and Force representing each sample",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "query": "from(bucket: \"arrays\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"arrays\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"angularVelocity\" or r[\"_field\"] == \"force\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: true)\r\n  |> yield(name: \"mean\")"
    }
   ]
  },
  {
   "title": "Displacement",
   "type": "timeseries",
   "description": "Array Values of Displacement",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "query": "from(bucket: \"arrays\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"arrays\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"displacement\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: true)\r\n  |> yield(name: \"mean\")"
    }
   ]
  },
  {
   "title": "Temperatures",
   "type": "stat",
   "description": "Temperatures of environment, motor bearing, and spindle bearing.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"static\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"mqtt_data\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"motorBearingT\" or r[\"_field\"] == \"environmentT\" or r[\"_field\"] == \"spindleBearingT\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: true)\r\n  |> yield(name: \"mean\")"
    }
   ]
  },
  {
   "title": "Welding times",
   "type": "bargauge",
   "description": "It shows the welding time of angular velocity, the welding time of force applied, and the difference between both.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"static\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"mqtt_data\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"welding_time_ang\" or r[\"_field\"] == \"welding_time_force\" or r[\"_field\"] == \"diff_force_ang\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: true)\r\n  |> yield(name: \"mean\")"
    }
   ]
  }
 ]
}