{
 "title": "Welding Machine Historic",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "5s",
 "panels": [
  { "type": "text", "gridPos": { "h": 2, "w": 24, "x": 0, "y": 0 }, "options": { "content": "# Backoffice View" } },
  {
   "title": "Total Welding Operations",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 0, "y": 2 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"static\")\r\n  |> range(start: 0) // Adjust the time range as needed (e.g., -30d for the last 30 days)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"mqtt_data\" and r[\"_field\"] == \"counter\")\r\n  |> count()\r\n"
    }
   ]
  },
  {
   "title": "Total Operation Time",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 6, "y": 2 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "query": "from(bucket: \"static\")\r\n  |> range(start: 0)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"mqtt_data\" and r[\"_field\"] == \"welding_total_time\")"
    }
   ]
  },
  {
   "title": "Applied Welding Force Distribution",
   "type": "histogram",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 2 },
   "fieldConfig": { "defaults": { "unit": "forceN" } },
   "targets": [
    {
     "query": "from(bucket: \"static\")\r\n  |> range(start: 0)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"mqtt_data\" and r[\"_field\"] == \"welding_time_force\")\r\n  |> keep(columns: [\"_time\", \"_value\"])\r\n"
    }
   ]
  },
  {
   "title": "Total Spinning Time",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 0, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "query": "from(bucket: \"static\")\r\n  |> range(start: 0) // Start from the earliest available data\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"mqtt_data\" and r[\"_field\"] == \"welding_time_ang\")"
    }
   ]
  },
  {
   "title": "Total Pressing Time",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 6, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "query": "from(bucket: \"static\")\r\n  |> range(start: 0) // Start from the earliest available data\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"mqtt_data\" and r[\"_field\"] == \"welding_time_force\")"
    }
   ]
  },
  {
   "title": "Min. Welding Temperatures",
   "type": "stat",
   "description": "Temperatures of environment, motor bearing, and spindle bearing.",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "min" ] } },
   "targets": [
    {
     "query": "from(bucket: \"static\")\r\n  |> range(start: 0)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"mqtt_data\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"motorBearingT\" or r[\"_field\"] == \"environmentT\" or r[\"_field\"] == \"spindleBearingT\")\r\n  |> map(fn: (r) => ({\r\n        r with \r\n        _field: if r[\"_field\"] == \"motorBearingT\" then \"Motor Bearing\"\r\n                else if r[\"_field\"] == \"environmentT\" then \"Environment\"\r\n                else if r[\"_field\"] == \"spindleBearingT\" then \"Spindle Bearing\"\r\n                else r[\"_field\"]\r\n    }))\r\n"
    }
   ]
  },
  {
   "title": "Average Welding Times",
   "type": "gauge",
   "description": "It shows the welding time of angular velocity, the welding time of force applied, and the difference between both.",
   "gridPos": { "h": 11, "w": 12, "x": 12, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "query": "from(bucket: \"static\")\r\n  |> range(start: 0)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"mqtt_data\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"welding_time_ang\" or r[\"_field\"] == \"welding_time_force\" or r[\"_field\"] == \"diff_force_ang\" or r[\"_field\"] == \"welding_total_time\")\r\n  |> map(fn: (r) => ({\r\n        r with \r\n        _field: if r[\"_field\"] == \"welding_time_ang\" then \"Spinning Duration\"\r\n                else if r[\"_field\"] == \"welding_time_force\" then \"Pressing Duration\"\r\n                else if r[\"_field\"] == \"diff_force_ang\" then \"Spinning-Force Delay\"\r\n                else if r[\"_field\"] == \"welding_total_time\" then \"Last Operation Duration\"\r\n                else r[\"_field\"]\r\n    }))\r\n"
    }
   ]
  },
  {
   "title": "Max. Welding Temperatures",
   "type": "stat",
   "description": "Temperatures of environment, motor bearing, and spindle bearing.",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "max" ] } },
   "targets": [
    {
     "query": "from(bucket: \"static\")\r\n  |> range(start: 0)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"mqtt_data\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"motorBearingT\" or r[\"_field\"] == \"environmentT\" or r[\"_field\"] == \"spindleBearingT\")\r\n  |> map(fn: (r) => ({\r\n        r with \r\n        _field: if r[\"_field\"] == \"motorBearingT\" then \"Motor Bearing\"\r\n                else if r[\"_field\"] == \"environmentT\" then \"Environment\"\r\n                else if r[\"_field\"] == \"spindleBearingT\" then \"Spindle Bearing\"\r\n                else r[\"_field\"]\r\n    }))\r\n"
    }
   ]
  }
 ]
}