{
 "title": "Welding Machine Live (Last Operation)",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "5s",
 "panels": [
  { "type": "text", "gridPos": { "h": 2, "w": 24, "x": 0, "y": 0 }, "options": { "content": "# Operator View" } },
  {
   "title": "Last welding times",
   "type": "gauge",
   "description": "It shows the welding time of angular velocity, the welding time of force applied, and the difference between both.",
   "gridPos": { "h": 12, "w": 12, "x": 0, "y": 2 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"static\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"mqtt_data\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"welding_time_ang\" or r[\"_field\"] == \"welding_time_force\" or r[\"_field\"] == \"diff_force_ang\" or r[\"_field\"] == \"welding_total_time\")\r\n  |> map(fn: (r) => ({\r\n        r with \r\n        _field: if r[\"_field\"] == \"welding_time_ang\" then \"Spinning Duration\"\r\n                else if r[\"_field\"] == \"welding_time_force\" then \"Pressing Duration\"\r\n                else if r[\"_field\"] == \"diff_force_ang\" then \"Spinning-Force Delay\"\r\n                else if r[\"_field\"] == \"welding_total_time\" then \"Last Operation Duration\"\r\n                else r[\"_field\"]\r\n    }))\r\n"
    }
   ]
  },
  {
   "title": "Last Welding Temperatures",
   "type": "stat",
   "description": "Temperatures of environment, motor bearing, and spindle bearing.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 2 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"static\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"mqtt_data\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"motorBearingT\" or r[\"_field\"] == \"environmentT\" or r[\"_field\"] == \"spindleBearingT\")\r\n  |> map(fn: (r) => ({\r\n        r with \r\n        _field: if r[\"_field\"] == \"motorBearingT\" then \"Motor Bearing\"\r\n                else if r[\"_field\"] == \"environmentT\" then \"Environment\"\r\n                else if r[\"_field\"] == \"spindleBearingT\" then \"Spindle Bearing\"\r\n                else r[\"_field\"]\r\n    }))\r\n"
    }
   ]
  },
  {
   "title": "Angular Velocity and Forces",
   "type": "timeseries",
   "description": "Arrays Values of Angular Velocity and Force representing each sample",
   "gridPos": { "h": 12, "w": 12, "x": 12, "y": 10 },
   "targets": [
    {
     "query": "from(bucket: \"arrays\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"arrays\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"angularVelocity\" or r[\"_field\"] == \"force\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: true)\r\n  |> yield(name: \"mean\")"
    }
   ]
  },
  {
   "title": "Displacement",
   "type": "timeseries",
   "description": "Array Values of Displacement",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 14 },
   "targets": [
    {
     "query": "from(bucket: \"arrays\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"arrays\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"displacement\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: true)\r\n  |> yield(name: \"mean\")"
    }
   ]
  }
 ]
}